services:

  frontend:
    stdin_open: true
    container_name: otty-frontend
    restart: unless-stopped
    build:
      context: otty-frontend
      dockerfile: Dockerfile
    volumes:
      - /otty-frontend/app/node_modules
      - /otty-frontend:/var/www/html/
    networks:
      - otty-network

  backend:
    build: otty-backend/php
    container_name: otty-backend
    restart: unless-stopped
    tty: true
    links:
      - db
    environment:
      APP_ENV: local
      SERVICE_NAME: backend
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    working_dir: /var/www/html/
    volumes:
      - ./otty-backend/php/app:/var/www/html/
      - ./otty-backend/php/app/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - otty-network
  websocket:
    build:
      context: otty-backend/nodejs
    container_name: websocket
    restart: unless-stopped
    ports:
      - "3005:3005"
    networks:
      - otty-network
  nginx:
    depends_on:
      - backend
      - frontend
      - websocket
    build:
      context: otty-backend/nginx
      dockerfile: Dockerfile
    container_name: otty-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "83:80"
    networks:
      - otty-network

  db:
    image: mysql:8
    container_name: otty-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./otty-backend/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      otty-network:

  cache:
    container_name: otty-cache
    image: memcached:1.6-alpine
    networks:
      otty-network:

volumes:
  dbdata:
    driver: local
  backend-vol:

networks:
  otty-network:
    driver: bridge