services:
  traefik:
    image: "traefik:v2.6"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "82:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    build: otty-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spa-to-http.rule=Host(`127.0.0.1`)"
      - "traefik.http.services.spa-to-http.loadbalancer.server.port=8080"
  nginx:
    build: otty-backend/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "83:83"
    volumes:
      - ./otty-backend/php/app/public:/var/www/html/app/public
#      - ./otty-backend/nginx/nginx.conf/:/etc/nginx/conf.d/


  php:
    build: otty-backend/php
    volumes:
      - ./otty-backend/php:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
      - cache
    ports:
      - "8003:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./otty-backend/mysql/my.cnf:/etc/mysql/my.cnf
  cache:
    image: memcached:1.6-alpine
volumes:
  dbdata:
    driver: local