services:
  nginx:
    build: otty-backend/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "83:83"
    volumes:
      - ./otty-backend/php/app/public:/var/www/html/app/public
#      - ./otty-backend/nginx/nginx.conf/:/etc/nginx/conf.d/

  frontend:
    build:
      context: ./otty-frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - ./otty-frontend/app:/app/otty-frontend
    depends_on:
      - php

  php:
    build: otty-backend/php
    volumes:
      - ./otty-backend/php:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
      - cache
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./otty-backend/mysql/my.cnf:/etc/mysql/my.cnf
  cache:
    image: memcached:1.6-alpine
volumes:
  dbdata:
    driver: local